**General Questions**

In [1]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [2]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [3]:
#Find the average age of students.
st_mean = data[:, 0].mean()
print(st_mean)

18.4


In [4]:
#Extract Math marks of all students.
math_marks = data[:,1]
print(math_marks)

[85 92 76 65 90]


In [5]:
#Find the highest Science mark.
print(data[:,2].max())

95


In [6]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]

array([[19, 92, 88]])

In [7]:
#Increase Math marks of all students by 5.
data[:,1] + 5

array([90, 97, 81, 70, 95])

In [8]:
#Find how many students are younger than 19.
data[data[:,0] < 19]

array([[18, 85, 78],
       [17, 76, 95],
       [18, 65, 70]])

In [9]:
#Calculate the average marks in each subject (column-wise mean).
print(data[:,1].mean())
print(data[:,2].mean())

81.6
83.2


In [10]:
#Get data of students who scored at least 80 in both subjects.
maths_gt_80 = data[:,1] > 80
science_gt_80 = data[:,2] > 80

data[maths_gt_80 & science_gt_80]

array([[19, 92, 88],
       [20, 90, 85]])

In [11]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])